# Generated by Django 5.2.1 on 2025-12-03 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tecnologia',
            },
        ),
        migrations.CreateModel(
            name='ImagemProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='projetos/galeria/')),
                ('legenda', models.CharField(blank=True, max_length=200, null=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='portifolio.projeto')),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='projetos', to='portifolio.tecnologia'),
        ),
    ]
